export type PrimeStatus = "BUY" | "SELL" | "WAIT" | "NO TRADE";
export type PrimeCandle = { datetime:string; open:number; high:number; low:number; close:number };
export type PrimeSignal = { symbol:string; status:PrimeStatus; bias:"BULLISH"|"BEARISH"|"NEUTRAL"; entry:number|null; sl:number|null; tp1:number|null; tp2:number|null; tp3:number|null; rr:number|null; confidence:number; regime:string; liquidity:string; reflexivity:string; orochi:string; vmap:string; trigger:string; risk:string; timeframes:Record<string,string>; generatedAt:string };

function ema(v:number[],p:number){if(v.length<p)return null;const k=2/(p+1);let x=v.slice(0,p).reduce((a,b)=>a+b,0)/p;for(let i=p;i<v.length;i++)x=v[i]*k+x*(1-k);return x}
function atr(c:PrimeCandle[],p=14){if(c.length<p+1)return null;const t:number[]=[];for(let i=1;i<c.length;i++){const x=c[i],q=c[i-1];t.push(Math.max(x.high-x.low,Math.abs(x.high-q.close),Math.abs(x.low-q.close)))}return t.slice(-p).reduce((a,b)=>a+b,0)/p}
function stage(c:PrimeCandle[]){const close=c.at(-1)?.close||0;const e20=ema(c.map(x=>x.close),20),e50=ema(c.map(x=>x.close),50);const h=c.slice(-10).map(x=>x.high),l=c.slice(-10).map(x=>x.low);const hh=Math.max(...h.slice(0,-1)),ll=Math.min(...l.slice(0,-1));const sweepUp=close>hh, sweepDown=close<ll;const trend=e20&&e50?(e20>e50&&close>e20?1:e20<e50&&close<e20?-1:0):0;const structure=trend>0&&h.at(-1)!>h[0]&&l.at(-1)!>l[0]?1:trend<0&&h.at(-1)!<h[0]&&l.at(-1)!<l[0]?-1:0;const liquidity=sweepDown?1:sweepUp?-1:0;const ref=(close-(c.at(-6)?.close||close))/(Math.max(atr(c,14)||1,0.000001));const reflex=ref>0.5?1:ref<-0.5?-1:0;const range=Math.max(...c.slice(-30).map(x=>x.high))-Math.min(...c.slice(-30).map(x=>x.low));const vmapBias=range>0?(close-(Math.min(...c.slice(-30).map(x=>x.low))+range/2))/(range/2):0;const vmap=vmapBias>0.15?1:vmapBias<-0.15?-1:0;return{trend,structure,liquidity,reflex,vmap,sweepUp,sweepDown}}

export function buildPrimeSignal(symbol:string,price:number,datasets:Record<string,PrimeCandle[]>):PrimeSignal{const entries=Object.entries(datasets).map(([tf,c])=>[tf,stage(c)] as const);const s=entries.map(([,x])=>x);const bull=s.filter(x=>x.trend>0).length,bear=s.filter(x=>x.trend<0).length;const bias=bull>bear?"BULLISH":bear>bull?"BEARISH":"NEUTRAL";const dir=bias==="BULLISH"?1:bias==="BEARISH"?-1:0;const aligned=s.filter(x=>x.trend===dir&&x.structure===dir&&x.vmap===dir).length;const liquidity=s.filter(x=>x.liquidity===dir).length;const reflex=s.filter(x=>x.reflex===dir).length;const score=Math.max(0,Math.min(100,45+aligned*12+liquidity*6+reflex*6));const vol=atr(Object.values(datasets).flat().slice(-120),14)||Math.max(price*.001,1);const riskMult=1.25;const entry=dir?price:null;const sl=dir?price-dir*vol*riskMult:null;const risk=sl?Math.abs(price-sl):null;const tp1=risk?price+dir*risk*1.5:null,tp2=risk?price+dir*risk*2:null,tp3=risk?price+dir*risk*3:null;let status:PrimeStatus="NO TRADE";if(dir&&aligned>=2&&liquidity>=1&&reflex>=1&&score>=78)status=dir>0?"BUY":"SELL";else if(dir&&score>=62)status="WAIT";const trigger=status==="BUY"||status==="SELL"?"REGIME + LIQUIDITY + REFLEXIVITY + OROCHI + VMAP aligned":"Required PRIME stages are not fully aligned";return{symbol,status,bias,entry,sl,tp1,tp2,tp3,rr:risk?1.5:null,confidence:Math.round(score),regime:dir?"TREND":"TRANSITION",liquidity:`sweeps=${s.filter(x=>x.liquidity!==0).length};confirmed=${liquidity}`,reflexivity:`direction=${dir};confirmed=${reflex}`,orochi:`structure_alignment=${aligned}`,vmap:aligned>0?"CONFIRMED_FILTER":"NOT_CONFIRMED",trigger,risk:status==="NO TRADE"?"Capital protection: no valid setup":"ATR-based SL; risk must be externally constrained",timeframes:Object.fromEntries(entries.map(([tf,x])=>[tf,`trend=${x.trend};structure=${x.structure};liquidity=${x.liquidity};reflex=${x.reflex};vmap=${x.vmap}`])),generatedAt:new Date().toISOString()}}
