export type SignalStatus = "BUY" | "SELL" | "WAIT" | "NO TRADE";
export type Candle = { datetime:string; open:number; high:number; low:number; close:number };
export type TimeframeAnalysis = { timeframe:string; trend:"BULLISH"|"BEARISH"|"NEUTRAL"; momentum:number; structure:"HH_HL"|"LH_LL"|"MIXED"; liquiditySweep:"BUY_SIDE"|"SELL_SIDE"|"NONE"; reflexivity:"BULLISH"|"BEARISH"|"NEUTRAL"; vmap:"BULLISH"|"BEARISH"|"NEUTRAL" };
export type IrenxSignal = { symbol:string; status:SignalStatus; bias:"BULLISH"|"BEARISH"|"NEUTRAL"; entry:number|null; sl:number|null; tp1:number|null; tp2:number|null; tp3:number|null; rr:number|null; confidence:number; trigger:string; regime:string; liquidity:string; reflexivity:string; orochi:string; vmap:string; timeframes:TimeframeAnalysis[]; generatedAt:string };

function ema(v:number[],p:number){if(v.length<p)return null;const k=2/(p+1);let x=v.slice(0,p).reduce((a,b)=>a+b,0)/p;for(let i=p;i<v.length;i++)x=v[i]*k+x*(1-k);return x}
function atr(c:Candle[],p=14){if(c.length<p+1)return null;const t:number[]=[];for(let i=1;i<c.length;i++){const x=c[i],q=c[i-1];t.push(Math.max(x.high-x.low,Math.abs(x.high-q.close),Math.abs(x.low-q.close)))}return t.slice(-p).reduce((a,b)=>a+b,0)/p}
function analyzeTimeframe(timeframe:string,c:Candle[]):TimeframeAnalysis{const close=c.at(-1)?.close||0,closes=c.map(x=>x.close),e20=ema(closes,20),e50=ema(closes,50);const trend=e20&&e50?(e20>e50&&close>e20?"BULLISH":e20<e50&&close<e20?"BEARISH":"NEUTRAL"):"NEUTRAL";const hs=c.slice(-8).map(x=>x.high),ls=c.slice(-8).map(x=>x.low);const structure=hs.at(-1)!>hs[0]&&ls.at(-1)!>ls[0]?"HH_HL":hs.at(-1)!<hs[0]&&ls.at(-1)!<ls[0]?"LH_LL":"MIXED";const prevHigh=Math.max(...c.slice(-8,-1).map(x=>x.high)),prevLow=Math.min(...c.slice(-8,-1).map(x=>x.low));const liquiditySweep=close>prevHigh?"SELL_SIDE":close<prevLow?"BUY_SIDE":"NONE";const a=atr(c,14)||Math.max(close*.001,1);const delta=close-(c.at(-6)?.close||close);const reflexivity=delta>a*.5?"BULLISH":delta<-a*.5?"BEARISH":"NEUTRAL";const range=Math.max(...c.slice(-30).map(x=>x.high))-Math.min(...c.slice(-30).map(x=>x.low));const mid=range?Math.min(...c.slice(-30).map(x=>x.low))+range/2:close;const vmap=close>mid+a*.15?"BULLISH":close<mid-a*.15?"BEARISH":"NEUTRAL";const momentum=e20&&e50?Math.max(-100,Math.min(100,((close-e50)/a)*10)):0;return{timeframe,trend,momentum:Number(momentum.toFixed(1)),structure,liquiditySweep,reflexivity,vmap}}

export function buildIrenxSignal(symbol:string,price:number,datasets:Record<string,Candle[]>):IrenxSignal{const analyses=Object.entries(datasets).map(([tf,c])=>analyzeTimeframe(tf,c));const bull=analyses.filter(a=>a.trend==="BULLISH").length,bear=analyses.filter(a=>a.trend==="BEARISH").length;const bias=bull>bear?"BULLISH":bear>bull?"BEARISH":"NEUTRAL";const dir=bias==="BULLISH"?1:bias==="BEARISH"?-1:0;const aligned=analyses.filter(a=>a.trend===bias&&a.structure===(dir>0?"HH_HL":dir<0?"LH_LL":"MIXED")).length;const liq=analyses.filter(a=>(dir>0&&a.liquiditySweep==="BUY_SIDE")||(dir<0&&a.liquiditySweep==="SELL_SIDE")).length;const reflex=analyses.filter(a=>(dir>0&&a.reflexivity==="BULLISH")||(dir<0&&a.reflexivity==="BEARISH")).length;const vm=analyses.filter(a=>(dir>0&&a.vmap==="BULLISH")||(dir<0&&a.vmap==="BEARISH")).length;let confidence=Math.min(97,40+aligned*12+liq*8+reflex*8+vm*8);const volatility=atr(Object.values(datasets).flat().slice(-120),14)||Math.max(price*.001,1);const entry=dir?price:null;const sl=dir?price-dir*volatility*1.25:null;const risk=sl?Math.abs(price-sl):null;const tp1=risk?price+dir*risk*1.5:null,tp2=risk?price+dir*risk*2:null,tp3=risk?price+dir*risk*3:null;let status:SignalStatus="NO TRADE";if(dir&&aligned>=2&&liq>=1&&reflex>=1&&vm>=1&&confidence>=78)status=dir>0?"BUY":"SELL";else if(dir&&confidence>=62)status="WAIT";const trigger=status==="BUY"||status==="SELL"?"REGIME → LIQUIDITY → REFLEXIVITY → OROCHI → VMAP confirmed":"PRIME chain incomplete — wait for confirmation";return{symbol,status,bias,entry,sl,tp1,tp2,tp3,rr:risk?1.5:null,confidence,trigger,regime:dir?"TREND":"TRANSITION",liquidity:`sweeps=${liq}/${analyses.length}; liquidity must agree with bias`,reflexivity:`confirmed=${reflex}/${analyses.length}; expansion/reversal pressure`,orochi:`structure=${aligned}/${analyses.length}; HH/HL or LH/LL alignment`,vmap:`${vm}/${analyses.length} timeframe confirmation; FILTER ONLY`,timeframes:analyses,generatedAt:new Date().toISOString()}}

export async function fetchTwelveDataCandles(symbol:string,interval:string,outputsize=180):Promise<Candle[]>{const apiKey=process.env.TWELVEDATA_API_KEY||"";if(!apiKey)throw new Error("TWELVEDATA_API_KEY is not configured");const providerSymbol=symbol==="XAUUSD"?"XAU/USD":symbol.includes("/")?symbol:symbol;const url=new URL("https://api.twelvedata.com/time_series");url.searchParams.set("symbol",providerSymbol);url.searchParams.set("interval",interval);url.searchParams.set("outputsize",String(Math.min(500,Math.max(60,outputsize))));url.searchParams.set("apikey",apiKey);const response=await fetch(url,{headers:{Accept:"application/json"},signal:AbortSignal.timeout(12000)});const data=await response.json() as any;if(!response.ok||data.status==="error"||!Array.isArray(data.values))throw new Error(data.message||`Twelve Data request failed with HTTP ${response.status}`);return data.values.reverse().map((v:any)=>({datetime:String(v.datetime),open:Number(v.open),high:Number(v.high),low:Number(v.low),close:Number(v.close)})).filter((c:Candle)=>[c.open,c.high,c.low,c.close].every(Number.isFinite))}
